config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'
  resources :cadastros

 

end

app/models/cadastro.rb
class Cadastro < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/cadastros_controller.rb
class CadastrosController < ApplicationController
  before_action :set_cadastro, only: [:show, :edit, :update, :destroy]

  # GET /cadastros
  # GET /cadastros.json
  def index
    @cadastros = Cadastro.all
  end

  # GET /cadastros/1
  # GET /cadastros/1.json
  def show
  end

  # GET /cadastros/new
  def new
    @cadastro = Cadastro.new
  end

  # GET /cadastros/1/edit
  def edit
  end

  # POST /cadastros
  # POST /cadastros.json
  def create
    @cadastro = Cadastro.new(cadastro_params)

    respond_to do |format|
      if @cadastro.save
        format.html { redirect_to @cadastro, notice: 'Cadastro was successfully created.' }
        format.json { render :show, status: :created, location: @cadastro }
      else
        format.html { render :new }
        format.json { render json: @cadastro.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cadastros/1
  # PATCH/PUT /cadastros/1.json
  def update
    respond_to do |format|
      if @cadastro.update(cadastro_params)
        format.html { redirect_to @cadastro, notice: 'Cadastro was successfully updated.' }
        format.json { render :show, status: :ok, location: @cadastro }
      else
        format.html { render :edit }
        format.json { render json: @cadastro.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cadastros/1
  # DELETE /cadastros/1.json
  def destroy
    @cadastro.destroy
    respond_to do |format|
      format.html { redirect_to cadastros_url, notice: 'Cadastro was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cadastro
      @cadastro = Cadastro.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cadastro_params
      params.require(:cadastro).permit(:dateC, :name, :proced, :hd, :obs, :dateE, :volume, :concent, :number, :local)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cadastros_helper.rb
module CadastrosHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/cadastros/_form.html.erb
<%= form_for(@cadastro) do |f| %>
  <% if @cadastro.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@cadastro.errors.count, "error") %> prohibited this cadastro from being saved:</h2>

      <ul>
      <% @cadastro.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label "Data da Coleta" %><br>
    <%= f.date_select :dateC, :order => [:day, :month, :year], use_month_numbers: true %>
  </div>
  <div class="field">
    <%= f.label "Nome" %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label "Procedência"%><br>
    <%= f.text_field :proced %>
  </div>
  <div class="field">
    <%= f.label "HD" %><br>
    <%= f.text_field :hd %>
  </div>
  <div class="field">
    <%= f.label :obs %><br>
    <%= f.text_area :obs %>
  </div>
  <div class="field">
    <%= f.label "Data da Extração" %><br>
    <%= f.date_select :dateE , :order => [:day, :month, :year], use_month_numbers: true%>
  </div>
  <div class="field">
    <%= f.label "Volume Extraído" %><br>
    <%= f.number_field :volume %> ml (ex: 10ul = 0,01ml)
    </div>
  <div class="field">
    <%= f.label "Concentração" %><br>
    <%= f.number_field :concent %>
  </div>
  <div class="field">
    <%= f.label "Número da Amostra" %><br>
    <%= f.text_field :number %>
  </div>
  <div class="field">
    <%= f.label "Local Armazenagem" %><br>
    <%= f.text_field :local %>
  </div>
  <div class="actions">
    <%= f.submit "Gravar Amostra" %>
  </div>
<% end %>

app/views/cadastros/edit.html.erb
<h1>Editando Amostra</h1>

<%= render 'form' %>

<%= link_to 'Exibir essa Amostra', @cadastro %> |
<%= link_to 'Listar Amostras', cadastros_path %>

app/views/cadastros/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listagem de Amostras</h1>

<%= link_to 'Nova Amostra', new_cadastro_path %>

<table data-role="table" data-mode="columntoggle" class="ui-responsive ui-shadow" id="myTable" data-filter="true" data-input="#filterTable-input">

  <thead>
    <tr>
      <th>Data da Coleta</th>
      <th>Nome</th>
      <th>Procedência</th>
      <th>HD</th>
      <th>Obs</th>
      <th>Data da Extração</th>
      <th>Volume Extraído</th>
      <th>Concentração</th>
      <th>Número da Amostra</th>
      <th>Local Armazenagem</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @cadastros.each do |cadastro| %>
      <tr>
        <td><%= cadastro.dateC %></td>
        <td><%= cadastro.name %></td>
        <td><%= cadastro.proced %></td>
        <td><%= cadastro.hd %></td>
        <td><%= cadastro.obs %></td>
        <td><%= cadastro.dateE %></td>
        <td><%= cadastro.volume %></td>
        <td><%= cadastro.concent %></td>
        <td><%= cadastro.number %></td>
        <td><%= cadastro.local %></td>
        <td><%= link_to 'Exibir', cadastro %></td>
        <td><%= link_to 'Editar', edit_cadastro_path(cadastro) %></td>
        <td><%= link_to 'Deletar', cadastro, method: :delete, data: { confirm: 'Tem certeza?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/cadastros/new.html.erb
<h1>Nova Amostra</h1>

<%= render 'form' %>

<%= link_to 'Voltar', cadastros_path %>

app/views/cadastros/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Data da Coleta:</strong>
  <%= @cadastro.dateC %>
</p>

<p>
  <strong>Nome:</strong>
  <%= @cadastro.name %>
</p>

<p>
  <strong>Procedência:</strong>
  <%= @cadastro.proced %>
</p>

<p>
  <strong>HD:</strong>
  <%= @cadastro.hd %>
</p>

<p>
  <strong>Obs:</strong>
  <%= @cadastro.obs %>
</p>

<p>
  <strong>Data da Extração:</strong>
  <%= @cadastro.dateE %>
</p>

<p>
  <strong>Volume Extraído:</strong>
  <%= @cadastro.volume %>
</p>

<p>
  <strong>Concentração:</strong>
  <%= @cadastro.concent %>
</p>

<p>
  <strong>Número da Amostra:</strong>
  <%= @cadastro.number %>
</p>

<p>
  <strong>Local Armazenagem:</strong>
  <%= @cadastro.local %>
</p>

<%= link_to 'Editar', edit_cadastro_path(@cadastro) %> |
<%= link_to 'Listar Amostras', cadastros_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Lcgm</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/welcome/index.html.erb
<h1>Bem vindo ao LCGM Database</h1>

<%= link_to "Relatório de Amostras", cadastros_path %>